# Generated by Django 2.1.3 on 2019-02-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_auto_20190131_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrs',
            name='can_change',
            field=models.BooleanField(default=True),
        ),
    ]
