# Generated by Django 2.1.3 on 2019-03-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FramePropVals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.FrameProps')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FrameVals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KeyframeSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveIntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskFrameSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propVal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.FramePropVals')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Projects'),
        ),
        migrations.AddField(
            model_name='taskframespec',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task'),
        ),
        migrations.AddField(
            model_name='keyframespec',
            name='frameSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.TaskFrameSpec'),
        ),
        migrations.AddField(
            model_name='framepropvals',
            name='val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.FrameVals'),
        ),
    ]
