# Generated by Django 2.1.3 on 2019-04-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20190325_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='has_score',
            field=models.BooleanField(default=False),
        ),
    ]
