# Generated by Django 2.1.3 on 2019-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_projects_has_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
