# Generated by Django 2.1.3 on 2019-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='color',
            field=models.CharField(default='#000000', max_length=256),
            preserve_default=False,
        ),
    ]
