# Generated by Django 2.1.3 on 2019-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_labels_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='category',
            field=models.CharField(default='category', max_length=256),
            preserve_default=False,
        ),
    ]
