# Generated by Django 2.1.3 on 2019-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_labels_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_viewed_frame',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
