# Generated by Django 2.1.3 on 2019-06-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0028_tasksource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Projects')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FrameProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.FrameProperties')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Projects')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=256)),
                ('catagory', models.CharField(default='category', max_length=256)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('attribute', models.CharField(max_length=256, null=True)),
                ('value', models.CharField(max_length=256, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.LabelTypes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Projects')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='framepropvals',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='framepropvals',
            name='val',
        ),
        migrations.RemoveField(
            model_name='labelattrs',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='labelattrs',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labelattrvalues',
            name='labelAttribute',
        ),
        migrations.RemoveField(
            model_name='labelattrvalues',
            name='value',
        ),
        migrations.AlterField(
            model_name='taskframespec',
            name='propVal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.FrameProperties'),
        ),
        migrations.DeleteModel(
            name='Attrs',
        ),
        migrations.DeleteModel(
            name='FrameProps',
        ),
        migrations.DeleteModel(
            name='FramePropVals',
        ),
        migrations.DeleteModel(
            name='FrameVals',
        ),
        migrations.DeleteModel(
            name='LabelAttrs',
        ),
        migrations.DeleteModel(
            name='LabelAttrValues',
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
        migrations.DeleteModel(
            name='Vals',
        ),
        migrations.AddField(
            model_name='labeldetails',
            name='labelType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabelTypes'),
        ),
        migrations.AddField(
            model_name='attributedetails',
            name='labelType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabelTypes'),
        ),
    ]
