# Generated by Django 2.1.3 on 2019-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0029_auto_20190618_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameproperties',
            name='value',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labeltypes',
            name='attribute',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labeltypes',
            name='value',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
