# Generated by Django 2.1.3 on 2019-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0031_task_video_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'project')},
        ),
    ]
