# Generated by Django 2.1.3 on 2020-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0032_auto_20190724_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='project',
        ),
        migrations.AddField(
            model_name='objectstorages',
            name='endpoint_url',
            field=models.CharField(default='example.com', max_length=256),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
